parameters:
  - name: "clientId"
    type: string
  - name: "tenantId"
    type: string
  - name: "clientSecret"
    type: string  
  - name: "resource"
    type: string  
    
steps:
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'
    
  - template: ../modulos/modulos-get-token-azure.yml
    parameters: 
            clientId: ${{parameters.clientId}}
            tenantId: ${{parameters.tenantId}}
            clientSecret: ${{parameters.clientSecret}}
            resource: ${{parameters.resource}}

  - template: ../modulos/term/modulos-create-terms.yml
    parameters:
            sourceFolder: $env:sourceFolderCreateTerm
            uriAPI: $env:uriAPICreateTerm
            endPoint: $env:endpoint

  #- template: ../modulos/term/modulos-update-terms.yml
  #  parameters:
  #          sourceFolder: $env:sourceFolderUpdateTerm
  #          uriAPI: $env:uriAPIUpdateTerm
  #           endPoint: $env:endpoint 
  

