# Module that assigns an entity to a term

# Required parameters to execute this template
parameters:
  - name: "sourceFolder"
    type: string
  - name: "uriAPI"
    type: string
  - name: "endPoint"
    type: string

# The 'steps' list define the tasks that will be executed in this template
steps:
  # Executes REST API call to assign an entity to a term
  - task: PowerShell@2
    displayName: Assign Entity To Term
    inputs:
      targetType: 'inline'
      script: |
        try{
        $Path = "$(System.ArtifactsDirectory)\${{parameters.sourceFolder}}"
        Write-Host "Path:" $Path
        $Body = Get-Content -Raw -Path $Path | ConvertFrom-Json
        Write-Host "Body:" $Body
        $BodyJson = $Body | ConvertTo-Json -AsArray
        Write-Host "BodyJson:" $BodyJson
        $URL = "${{parameters.endPoint}}${{parameters.uriAPI}}"
        $varUrl = $URL.replace('GuidEntity',"$env:AzGuidTerm")
        Write-Host "URL:" $varUrl
        Invoke-RestMethod -Uri "$varUrl" -Method "POST" -Headers @{Authorization = $env:AzToken} -ContentType "application/json" -Body $BodyJson -Verbose
        }
        catch {
            Write-Output "Fail to backup model"
            Write-Output "Exception" $_.Exception
            Write-Output "Exception.Message" $_.Exception.Message
            Write-Output "Exception.StackTrace" $_.Exception.StackTrace
            exit 1
        }
      pwsh: true
         